### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [pnorman/openstreetmap-carto-client#15]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by pnorman** [comment]
Given I'm not actively working on this at all, I doubt I will.

**Comment by danieldegroot2** [comment]
Ok, thanks for the reply. :-)
