### ISSUE TITLE
Tile Schema

### ISSUE THREAD

**Issue by Bibi56** [pnorman/openstreetmap-carto-client#4]
Vector tiles usually preserve the "good old" OSM zoom level.
Can't you preserve it? IMHO it would make (our ;-)) live easier.

**Comment by pnorman** [comment]
I assume you're talking about the relationship between scale and zoom, and tiles taking 512px? This is important and necessary, and 512px vector tiles are standard.

**Comment by Bibi56** [comment]
Sorry for the late answer, I wanted to check a MapTiler. A vector tile has no size by definition (even if with the snap points you're right of course, but with data from zoom level 15 to 20 are usually in the zoom level 14 so the precision of tile 14 is sufficient up to zoom level 20).
And yes I did expect 256 pixel tiles. With MapTiler, if rendered on the server (transferred as bitmap) or on the client (transferred as mvt) I get the same result in term of Z/X/Y. Maybe they send 512 pixel tiles even for server side rendering.
