### ISSUE TITLE
Current filtering leads to huge gaps in landcover data

### ISSUE THREAD

**Issue by jeisenbe** [pnorman/openstreetmap-carto-client#5]
Many areas of landcover such as `landuse=meadow` and `landuse=farmland` are mapped in small parcels, especially in places like the Netherlands (where this data has been imported), but also in places where the traditional landscape consists of many small areas of different agricultural use (like in the Azores). 

I expect that generalization might be necessary, since the rendering speed of this style at ~z7/z8 is already quite poor even with the current filtering

Another option would be to render the water and landcover as raster image for lower zoom levels, as done by the fr.openstreetmap.org style currently.

Netherlands rendering in this style:
<img width="645" alt="Screen Shot 2020-11-08 at 09 57 01" src="https://user-images.githubusercontent.com/42757252/98473374-e334a580-21a9-11eb-848c-43ec77df3458.png">

<img width="1022" alt="Screen Shot 2020-11-08 at 09 57 16" src="https://user-images.githubusercontent.com/42757252/98473172-d2842f80-21a9-11eb-94e4-28d8ddf170be.png">

Compared with current Openstreetmap Carto rendering:
<img width="617" alt="Screen Shot 2020-11-08 at 09 58 28" src="https://user-images.githubusercontent.com/42757252/98473805-04959180-21aa-11eb-9db2-3986c871ee9d.png”>

<img width="1022" alt="Screen Shot 2020-11-08 at 09 58 18" src="https://user-images.githubusercontent.com/42757252/98473826-05c6be80-21aa-11eb-93db-328ce5657599.png">

Azores current rendering:
<img width="223" alt="Screen Shot 2020-11-08 at 10 02 39" src="https://user-images.githubusercontent.com/42757252/98474092-1bd47f00-21aa-11eb-8aa1-2df590a6f45d.png">

Compared with OpenStreetMap Carto:
<img width="223" alt="Screen Shot 2020-11-08 at 10 02 51" src="https://user-images.githubusercontent.com/42757252/98474210-24c55080-21aa-11eb-9a0d-c3d39cbe5ce9.png">

**Comment by pnorman** [comment]
I suspect I'm going to have to drop this data at those zooms to proceed with other work

**Comment by jeisenbe** [comment]
Is it infeasible to use a raster background or another form of preprocessed
data as a workaround?

>

**Comment by pnorman** [comment]
Dropped the filtering for now. I'll have to revisit later.
