### ISSUE TITLE
Figure out renderer license situation

### ISSUE THREAD

**Issue by pnorman** [pnorman/openstreetmap-carto-client#7]
With Mapbox GL JS being un-open sourced, I need to figure out what rendering engine this project will continue with.

It could build off of 
- https://github.com/mapbox/mapbox-gl-js/tree/3136a53235cf17b732e84c9945c4e85ba3369a93, the last Mapbox GL JS version under an open-source license;
- another rendering engine that uses Mapbox GL styles; or
- something new.

**Comment by bryceco** [comment]
There’s some discussion of alternatives [here](https://news.ycombinator.com/item?id=25347310)

**Comment by pnorman** [comment]
MapLibre is the standard now.
